services:
  - type: web
    name: tds-virtual-ta
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OLLAMA_BASE_URL
        value: http://localhost:11434
    plan: free
